name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: ieatcheese99
          outputs: github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --local user.email "harjatizabdan@gmail.com"
          git config --local user.name "ieatcheese99"
          if [ -f "github-contribution-grid-snake.svg" ]; then
            git add github-contribution-grid-snake.svg
            git commit -m "chore: update snake animation"
            git push
          fi
